name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ÉTAPE CRUCIALE : Installer Java 17 pour Gradle 8.6
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Configuration de Flutter 3.2.6
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.2.6'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # Build de la version Web (indispensable pour GitHub Pages)
      - name: Build Web
        run: flutter build web --release --base-href "/akasuts/"

      # Déploiement automatique sur la branche gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web